### ISSUE TITLE
How do I change the compute for codebuild?

### ISSUE THREAD

**Issue by Taikono-Himazin** [tmokmss/deploy-time-build#19]
The standard 3 GB memory and 2 vCPU are not enough.
I want to upgrade to 7 GB memory and 4 vCPU,
but it seems there is no option for that. How can I change it?

**Comment by tmokmss** [comment]
I suppose you are using `NodejsBuild`. You can change the compute type via property override:

```ts
    const build = new NodejsBuild(this, "ReactBuild", {
      // ...
    });
    (
      build.node.findChild("Project").node.defaultChild as CfnResource
    ).addPropertyOverride("Environment.ComputeType", ComputeType.MEDIUM);
```

**Comment by tmokmss** [comment]
@Taikono-Himazin Does it solve your problem? I'll close this issue but please feel free to contact me if you have any further problem.
