### ISSUE TITLE
platform specific path delimiter issue

### ISSUE THREAD

**Issue by Ajido** [tmokmss/deploy-time-build#6]
deploy from windows, it fails 🙏 

https://github.com/tmokmss/deploy-time-build/blob/3fe33804d2de6ff839e52b1559a4077007c9ff34/src/nodejs-build.ts#L226
![image](https://github.com/tmokmss/deploy-time-build/assets/206827/8909c6db-489a-4f9b-8d72-0866172e915c)

**Comment by tmokmss** [comment]
Thanks, it should work now :)
