### ISSUE TITLE
Unable to add Roles/permissions to code artifact

### ISSUE THREAD

**Issue by MattBodey** [tmokmss/deploy-time-build#8]
### Issue

In our AWS account, we deploy packages to a CodeArtifact domain that are used as part of the build process. 

When we try and run CodeArtifact login, we get an error message due to the code deploy project that is bundling the code not having permissions to get a token from CodeArtifact. 

`An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn:aws:sts::<account>:assumed-role/<buildRole>/AWSCodeBuild-5a741022-3f12-4010-ab11-2ffbf0169442 is not authorized to perform: codeartifact:GetAuthorizationToken on resource: arn:aws:codeartifact:<region>:<account>:domain/<domain> because no identity-based policy allows the codeartifact:GetAuthorizationToken action`

### Requirement

Would it be possible to expose a way of attaching permissions to the CodeDeploy project to enable permission for accessing private CodeArtifact domains

**Comment by tmokmss** [comment]
Hi @MattBodey, thanks for sharing your use case :)

Now that `NodejsBuild` implements `IGrantable`, you should be able to add IAM policies to the build environment:
https://github.com/tmokmss/deploy-time-build#allowing-access-from-the-build-environment-to-other-aws-resources

Please let me know if it doesn't work, thanks!
